### ISSUE TITLE
Links to notebook files incorrectly use .md extension instead of .ipynb

### ISSUE THREAD

**Issue by Anushkarshetty45** [huggingface/doc-builder#568]
## Description
When using doc-builder with `convert_notebooks: true`, the links at the bottom of articles incorrectly point to `.md` files when they should be pointing to `.ipynb` files.

## Steps to reproduce
1. Enable notebook conversion in the workflow file:
```yaml
jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      convert_notebooks: true
      # other parameters...
```
2. Build documentation that contains Jupyter notebooks
3. Check the links at the bottom of the generated documentation

## Current behavior
Links at the bottom of articles point to files with `.md` extension, for example:
`[Some notebook title](notebook_name.md)`

## Expected behavior
Links should point to the original `.ipynb` files, for example:
`[Some notebook title](notebook_name.ipynb)`

## Additional context
- This issue affects all notebook files that are converted to MDX
- The incorrect extension makes it harder for users to find and access the original notebook files
- Example repository demonstrating the issue: huggingface/cookbook (see issue #181)

## Environment
- doc-builder version: latest
- Using GitHub Actions workflow for documentation building
